---
abstract: 'Utility functions for CPAN Testers modules'
author:
  - 'David A Golden <dagolden@cpan>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101540, CPAN::Meta::Converter version 2.101461'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Testers-Common-Utils
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  CPAN::Testers::Common::Utils:
    file: lib/CPAN/Testers/Common/Utils.pm
    version: 0.002
requires:
  Exporter: 0
  perl: 5.006
resources:
  repository: http://github.com/dagolden/cpan-testers-common-utils
version: 0.002
